name: versioning
description: A CLI app to help you manage versioning on your packages
version: 0.1.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.15.1 <3.0.0'

executables:
  versioning: versioning

dependencies:

dev_dependencies:
  lints: 1.0.1
  test: 1.20.1
