name: Package Deployment

on:
  pull_request:
    branches: [ main ]

jobs:
  analyze:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v2
      - uses: dart-lang/setup-dart@9a04e6d73cca37bd455e0608d7e5092f881fd603
        with:
          sdk: 2.15.1
      - name: Install dependencies
        run: dart pub get
      - name: Analyze project source
        run: dart analyze --fatal-infos
      - name: Run tests
        run: dart test

  deploy:
    runs-on: windows-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v2
      - uses: dart-lang/setup-dart@9a04e6d73cca37bd455e0608d7e5092f881fd603
        with:
          sdk: 2.15.1
      - name: Install dependencies
        run: dart pub get
      - name: Build
        run: ./build.sh
      - name: Publish on Releases
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: ./deploy.sh
