name: Package Deployment

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    uses: versioning-cli/versioning-app/.github/workflows/analyze.yaml@main
    timeout-minutes: 5
  deploy:
    runs-on: windows-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v2
      - uses: dart-lang/setup-dart@9a04e6d73cca37bd455e0608d7e5092f881fd603
        with:
          sdk: 2.15.1
      - name: Install dependencies
        run: dart pub get
      - name: Build
        run: dart compile exe bin/app.dart -o versioning.exe
